### ISSUE TITLE
Issue with grids

### ISSUE THREAD

**Issue by VanshitaGandhi** [VanshitaGandhi/components-on-a-grid#1]
@HannahDelaney @hellachella

**Comment by hellachella** [comment]
Please describe the issue you are having, and include a screenshot of how it currently looks in the browser.

**Comment by VanshitaGandhi** [comment]
Hi, I have the following queries:

1) How to get even spacing between the nav li's
2) I'm trying to use grid-template-areas for the second section, and both the figures either stack themselves on the left hand side or the right hand side and not beside each other.

I've pushed my code so you can have a look at it.

Thank you. @hellachella 

<img width="1680" alt="Screenshot 2020-09-16 at 8 34 56 PM" src="https://user-images.githubusercontent.com/55109487/93405862-33535380-f85c-11ea-989b-0c4c32c499d0.png">
<img width="1566" alt="Screenshot 2020-09-16 at 8 35 25 PM" src="https://user-images.githubusercontent.com/55109487/93405869-36e6da80-f85c-11ea-8163-ab3e0325ddea.png">
<img width="1589" alt="Screenshot 2020-09-16 at 8 35 32 PM" src="https://user-images.githubusercontent.com/55109487/93405874-38b09e00-f85c-11ea-9a37-3a3d0423f038.png">

**Comment by VanshitaGandhi** [comment]
Hi, I solved it, so I'll just close this issue.
Thanks. @hellachella
